[general]
import = [
  "~/.config/alacritty/themes/themes/_active.toml"
]
live_config_reload = true

[window]
decorations = "none"
opacity = 1
startup_mode = "Windowed"
[font]
size = 12.0

[font.normal]
#family = "Hack Nerd Font Mono"
