# The following lines were added by compinstall
#
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

zstyle :compinstall filename '/home/massi/.zshrc'

autoload -Uz compinit
compinit

autoload -U colors
colors

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep nomatch
unsetopt appendhistory autocd extendedglob notify
bindkey -e
# End of lines configured by zsh-newuser-install

export EDITOR=vim

export CDPATH=.:$HOME:$HOME/src

# Reverse search key binding
bindkey '^R' history-incremental-search-backward

# Aliases
source $HOME/.shell_aliases/shell_aliases

set -o vi

# Path
path+=($HOME/.local/bin)
path+=($HOME/.krew/bin)
path+=($HOME/go/bin)

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Direnv
 eval "$(direnv hook zsh)"

# Bare plugins

# Kubectl prompt
source $HOME/.zsh-kubectl-prompt/kubectl.zsh
function kubectl_prompt() {
	local color="blue"

	if [[ "$ZSH_KUBECTL_USER" =~ "admin" ]]; then
		color=red
	fi

	echo "%{$fg[$color]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}"
}
RPROMPT='$(kubectl_prompt)%F{blue}[%F{green}%D{%H:%M:%S}%F{blue}]%f'
