# The following lines were added by compinstall
#
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

zstyle :compinstall filename "${HOME}/.zshrc"

autoload -Uz compinit
compinit

autoload -U colors
colors

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep nomatch
unsetopt appendhistory autocd extendedglob notify
bindkey -e
# End of lines configured by zsh-newuser-install

export EDITOR=vim

export CDPATH=.:$HOME:$HOME/src:$HOME/src/github.com:$HOME/src/github.com/maxgio92:$HOME/src/github.com/chainguard-images:$HOME/src/github.com/chainguard-dev:$HOME/src/github.com/wolfi-dev

export GIT_CODE_FOLDER="${HOME}/src"

# Reverse search key binding
bindkey '^R' history-incremental-search-backward

# Aliases
source $HOME/.shell_aliases/shell_aliases

set -o vi

# Path
path+=($HOME/.local/bin)
path+=($HOME/.krew/bin)
path+=($HOME/go/bin)
path+=($HOME/.git-dclone)

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Setup Brew bins in PATH
[ -d /home/linuxbrew ] && \
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Direnv
 eval "$(direnv hook zsh)"

export WORKSTATION_USER=massimiliano-giovagnoli

# The next line updates PATH for the Google Cloud SDK.
[ -f "$HOME/.local/google-cloud-sdk/path.zsh.inc" ] && \
	. '/var/home/massimiliano.giovagnoli/.local/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
[ -f "$HOME/.local/google-cloud-sdk/completion.zsh.inc" ] && \
	. '/var/home/massimiliano.giovagnoli/.local/google-cloud-sdk/completion.zsh.inc'
