#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export BASH_ENV=${HOME}/.bash_aliases
export GOPATH=${HOME}/workspace/go

KREWPATH=${HOME}/.krew/bin
TFENVPATH=${HOME}/.tfenv/bin
LOCALPATH=${HOME}/.local/bin
GOBIN=${GOPATH}/bin

CUSTOMPATHS=${LOCALPATH}:${TFENVPATH}:${GOBIN}:${KREWPATH}

export PATH=${PATH}:${CUSTOMPATHS}
