#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export BASH_ENV=~/.bash_aliases
export PATH=$PATH:~/.local/bin
export GOPATH=$HOME/workspace/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export KREW_ROOT=$HOME/.krew
export PATH=$PATH:$KREW_ROOT/bin
