#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export BASH_ENV=${HOME}/.bash_aliases
export GOPATH=${HOME}/src/go

KREWPATH=${HOME}/.krew/bin
TFENVPATH=${HOME}/.tfenv/bin
LOCALPATH=${HOME}/.local/bin
GOBIN=${GOPATH}/bin
GOGLOBALBIN=/usr/local/go/bin
KUBEBUILDERPATH=/usr/local/kubebuilder/bin

CUSTOMPATHS=${LOCALPATH}:${TFENVPATH}:${GOBIN}:${KREWPATH}:${GOGLOBALBIN}:${KUBEBUILDERPATH}

export PATH=${PATH}:${CUSTOMPATHS}
