# Aliases

shopt -s expand_aliases
#alias ls='ls -G' # Enable colorized output for MacOS
alias ls='ls --color' # Enable colorized output for Linux
alias grep='grep --color' # Enable colorized output
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias k='kubectl'
alias kns='kubens'
alias kctx='kubectx'
alias aws="docker run --rm -it -v ~/.aws:/root/.aws -e AWS_PROFILE amazon/aws-cli"
alias ddr="sudo dockerd -p /var/run/docker.pid > /var/log/docker.log 2>&1 &"
alias vimfzf="vim -o $(fzf)"
alias batfzf="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"
alias screencap='grim -g "$(slurp)" screenshot_$(date +%Y%m%d_%H%M%S).png'
